server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 119.23.66.181:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
