spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://119.23.66.181:9411
  sleuth:
    sampler:
      probability: 1

server:
  port: 10086

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

